% 输入
% % struct GA_paras = {'snvarsnvars','sLB','sUB','spopsize','smaxGene' }
% % Fit_paras = struct('sNCBP',[NCBP_min,NCBP_max],'sGBest_Curr', GBest(iteration),...
%                     'sSizePSO',[size_particle,dim_objfunction],...
%                     'sc1_local_current',c1_local(:,iteration),'sc2_global_current',c2_global(:,iteration), ...
%                     'sV_Curr', V(:,:,iteration), 'sParticles_Curr', Particles(:,:,iteration), ...
%                     'slocal_minimum_particle_Curr', local_minimum_particle(:,:,iteration) , ...
%                     'sglobal_minimum_particle_Curr', global_minimum_particle(:,:,iteration), ... 
%                     'sabs_max_V', abs_max_V, 'sabs_max_particle',abs_max_particle,...
%                     'sLBest_Curr', LBest(:,iteration),'sW_Current',W(1,1,iteration));
% % Fitness 当前种群的适应度值
% 限制最大最小取值范围，轮盘选择，适应变异，
% 包括选择，交叉，变异三步遗传操作,采用传进来的适应度函数值完成遗传操作，输出操作得到的种群和适应度函数值，以及最优个体的索引

function [POPULATION, FVAL, Best_Index] =  myGA( GA_paras, Fit_paras, Fitness)




